import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TanstackProvider } from "../utils/ReactQueryProviders";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Books Library",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-image-full`} // <-- Apply the fixed background class
      >
        {/*
          2. Add a wrapper div to create the glass pane effect.
          This div is *on top* of the background image, and the backdrop-blur
          utility blurs the image that is visible *behind* it.
        */}
        <div className=""> 
          <TanstackProvider>{children}</TanstackProvider>
        </div>
      </body>
    </html>
  );
}
